# Default values for anairecloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Your VM Public IPv4 address or Public IPv4 DNS
publicIP: sensor.aireciudadano.com

#Your Grafana admin password
grafanaAdminPass: yourgrafanaadminpassword

#If there is a letsencrypt certificate prepared to be used by nginx in /data/letsencrypt set this var to true
tls: true

smtp_enabled: false
smtp_host: smtp.example.com:587
smtp_user: myuser@example.com
smtp_pass: yourmailpassword
smtp_from: your sender name

#Resorces for PODS. The idea is to be able to increase resources when running in a more powerful VM
#These values are valid for a VM with 2CPU and 4GiB. Keep in mind these are the minimum requirements.
resources:
  mqttbroker:
    requests:
      memory: "100Mi"
      cpu: "50m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "200Mi"
  mqttforward:
    requests:
      memory: "100Mi"
      cpu: "50m"
      ephemeral-storage: "120Mi"
    limits:
      memory: "120Mi"
      cpu: "100m"
      ephemeral-storage: "150Mi"
  pushgateway:
    requests:
      memory: "100Mi"
      cpu: "80m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "200Mi"
  prometheus:
    requests:
      memory: "800Mi"
      cpu: "200m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "1Gi"
      cpu: "400m"
      ephemeral-storage: "1.2Gi"
  grafana:
    requests:
      memory: "300Mi"
      cpu: "150m"
      ephemeral-storage: "500Mi"
    limits:
      memory: "500Mi"
      cpu: "250m"
      ephemeral-storage: "600Mi"
  apiserver:
    requests:
      memory: "100Mi"
      cpu: "60m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "200Mi"
  cleanercronjob:
    requests:
      memory: "50Mi"
      cpu: "50m"
      ephemeral-storage: "80Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
      ephemeral-storage: "120Mi"
  nginx:
    requests:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "200Mi"
      cpu: "150m"
      ephemeral-storage: "250Mi"