# Default values for anairecloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Your VM Public IPv4 address or Public IPv4 DNS
publicIP: sensor.aireciudadano.com

#Your Grafana admin password
grafanaAdminPass: yourgrafanaadminpassword

#If there is a letsencrypt certificate prepared to be used by nginx in /data/letsencrypt set this var to true
tls: false

smtp_enabled: false
smtp_host: smtp.example.com:587
smtp_user: myuser@example.com
smtp_pass: yourmailpassword
smtp_from: your sender name

#Resorces for PODS. The idea is to be able to increase resources when running in a more powerful VM
#These values are valid for a VM with 2CPU and 4GiB. Keep in mind these are the minimum requirements.
resources:
  mqttbroker:
    requests:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "250Mi"
    limits:
      memory: "250Mi"
      cpu: "150m"
      ephemeral-storage: "350Mi"
  mqttforward:
    requests:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "200Mi"
    limits:
      memory: "250Mi"
      cpu: "150m"
      ephemeral-storage: "350Mi"
  pushgateway:
    requests:
      memory: "150Mi"
      cpu: "300m"
      ephemeral-storage: "300Mi"
    limits:
      memory: "250Mi"
      cpu: "400m"
      ephemeral-storage: "400Mi"
  prometheus:
    requests:
      memory: "1.2Gi"
      cpu: "300m"
      ephemeral-storage: "1.5Gi"
    limits:
      memory: "1.6Gi"
      cpu: "500m"
      ephemeral-storage: "1.8Gi"
  grafana:
    requests:
      memory: "1Gi"
      cpu: "300m"
      ephemeral-storage: "1.4Gi"
    limits:
      memory: "1.4Gi"
      cpu: "700m"
      ephemeral-storage: "1.8Gi"
  apiserver:
    requests:
      memory: "200Mi"
      cpu: "150m"
      ephemeral-storage: "300Mi"
    limits:
      memory: "300Mi"
      cpu: "250m"
      ephemeral-storage: "450Mi"
  cleanercronjob:
    requests:
      memory: "100Mi"
      cpu: "150m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "200Mi"
      cpu: "200m"
      ephemeral-storage: "300Mi"
  nginx:
    requests:
      memory: "300Mi"
      cpu: "200m"
      ephemeral-storage: "350Mi"
    limits:
      memory: "450Mi"
      cpu: "300m"
      ephemeral-storage: "550Mi"