# Default values for anairecloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Your VM Public IPv4 address or Public IPv4 DNS
publicIP: sensor.aireciudadano.org

#If a secondary IPv4 or dns is used uncomment the following variable
#secondaryPublicIP: sensor.aireciudadano.org


#Your Grafana admin password
grafanaAdminPass: yourgrafanaadminpassword

#If there is a letsencrypt certificate prepared to be used by nginx in /data/letsencrypt set this var to true
tls: true

smtp_enabled: false
smtp_host: smtp.example.com:587
smtp_user: myuser@example.com
smtp_pass: yourmailpassword
smtp_from: your sender name

#Resorces for PODS. The idea is to be able to increase resources when running in a more powerful VM
#These values are valid for a VM with 2CPU and 4GiB. Keep in mind these are the minimum requirements.
resources:
  mqttbroker:
    requests:
      memory: "50Mi"
      cpu: "50m"
#      ephemeral-storage: "200Mi"
    limits:
      memory: "70Mi"
      cpu: "100m"
#      ephemeral-storage: "300Mi"
  mqttforward:
    requests:
      memory: "100Mi"
      cpu: "50m"
#      ephemeral-storage: "200Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "300Mi"
  pushgateway:
    requests:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "100Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "400Mi"
  prometheus:
    requests:
      memory: "512Mi"
      cpu: "100m"
#      ephemeral-storage: "1Gi"
    limits:
      memory: "512Mi"
      cpu: "500m"
#      ephemeral-storage: "1.5Gi"
  grafana:
    requests:
      memory: "256Mi"
      cpu: "100m"
#      ephemeral-storage: "700Mi"
    limits:
      memory: "256Mi"
      cpu: "500m"
#      ephemeral-storage: "1Gi"
  grafanaimagerenderer:
    requests:
      memory: "1Gi"
      cpu: "500m"
#      ephemeral-storage: "2Gi"
    limits:
      memory: "1Gi"
      cpu: "500m"
#      ephemeral-storage: "2.5Gi"
  apiserver:
    requests:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "200Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "400Mi"
  cleanercronjob:
    requests:
      memory: "50Mi"
      cpu: "100m"
#      ephemeral-storage: "200Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "300Mi"
  nginx:
    requests:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "250Mi"
    limits:
      memory: "100Mi"
      cpu: "100m"
#      ephemeral-storage: "400Mi"