# Default values for anairecloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Your VM Public IPv4 address or Public IPv4 DNS
publicIP: sensor.aireciudadano.com

#Your Grafana admin password
grafanaAdminPass: yourgrafanaadminpassword

#If there is a letsencrypt certificate prepared to be used by nginx in /data/letsencrypt set this var to true
tls: true

smtp_enabled: false
smtp_host: smtp.example.com:587
smtp_user: myuser@example.com
smtp_pass: yourmailpassword
smtp_from: your sender name

#Resorces for PODS. The idea is to be able to increase resources when running in a more powerful VM
#These values are valid for a VM with 2CPU and 4GiB. Keep in mind these are the minimum requirements.
resources:
  mqttbroker:
    requests:
      memory: "200Mi"
      cpu: "120m"
    limits:
      memory: "250Mi"
      cpu: "200m"
  mqttforward:
    requests:
      memory: "150Mi"
      cpu: "150m"
    limits:
      memory: "180Mi"
      cpu: "200m"
  pushgateway:
    requests:
      memory: "200Mi"
      cpu: "250m"
    limits:
      memory: "250Mi"
      cpu: "350m"
  prometheus:
    requests:
      memory: "1Gi"
      cpu: "300m"
    limits:
      memory: "1.5Gi"
      cpu: "500m"
  grafana:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "500Mi"
      cpu: "250m"
  apiserver:
    requests:
      memory: "100Mi"
      cpu: "80m"
    limits:
      memory: "150Mi"
      cpu: "100m"
  cleanercronjob:
    requests:
      memory: "150Mi"
      cpu: "200m"
    limits:
      memory: "200Mi"
      cpu: "250m"
  nginx:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "250m"