# Default values for anairecloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Your VM Public IPv4 address or Public IPv4 DNS
publicIP: sensor.aireciudadano.org

#If a secondary IPv4 or dns is used uncomment the following variable
#secondaryPublicIP: sensor.aireciudadano.org


#Your Grafana admin password
grafanaAdminPass: yourgrafanaadminpassword

#If there is a letsencrypt certificate prepared to be used by nginx in /data/letsencrypt set this var to true
tls: true

smtp_enabled: false
smtp_host: smtp.example.com:587
smtp_user: myuser@example.com
smtp_pass: yourmailpassword
smtp_from: your sender name

#Resorces for PODS. The idea is to be able to increase resources when running in a more powerful VM
#These values are valid for a VM with 2CPU and 4GiB. Keep in mind these are the minimum requirements.
resources:
  mqttbroker:
    requests:
      memory: "100Mi"
      cpu: "65m"
      ephemeral-storage: "200Mi"
    limits:
      memory: "150Mi"
      cpu: "125m"
      ephemeral-storage: "300Mi"
  mqttforward:
    requests:
      memory: "150Mi"
      cpu: "65m"
      ephemeral-storage: "200Mi"
    limits:
      memory: "200Mi"
      cpu: "125m"
      ephemeral-storage: "300Mi"
  pushgateway:
    requests:
      memory: "150Mi"
      cpu: "125m"                        #Debe ser minimo 125 sino no borra luego el pushgateway cleaner
      ephemeral-storage: "300Mi"
    limits:
      memory: "250Mi"
      cpu: "200m"
      ephemeral-storage: "400Mi"
  prometheus:
    requests:
      memory: "700Mi"
      cpu: "300m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "1Gi"
      cpu: "400m"
      ephemeral-storage: "1.2Gi"
  grafana:
    requests:
      memory: "750Mi"
      cpu: "350m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "1Gi"
      cpu: "500m"
      ephemeral-storage: "1.2Gi"
  grafanaimagerenderer:
    requests:
      memory: "900Mi"
      cpu: "230m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "1Gi"
      cpu: "350m"
      ephemeral-storage: "1.2Gi"
  apiserver:
    requests:
      memory: "150Mi"
      cpu: "100m"
      ephemeral-storage: "200Mi"
    limits:
      memory: "250Mi"
      cpu: "150m"
      ephemeral-storage: "400Mi"
  cleanercronjob:
    requests:
      memory: "75Mi"
      cpu: "120m"
      ephemeral-storage: "150Mi"
    limits:
      memory: "150Mi"
      cpu: "170m"
      ephemeral-storage: "300Mi"
  nginx:
    requests:
      memory: "200Mi"
      cpu: "140m"
      ephemeral-storage: "350Mi"
    limits:
      memory: "300Mi"
      cpu: "250m"
      ephemeral-storage: "450Mi"