apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttbroker
  template:
    metadata:
      labels:
        app: mqttbroker
    spec:
      containers:
        - name: mqttbroker
          image: eclipse-mosquitto:1.6.14
          command:
            - "/usr/sbin/mosquitto"
            - "-c"
            - "/mosquitto/config/mosquitto.conf"
          volumeMounts:
            - name: mqtt-storage-volume
              mountPath: /mosquitto/data
            - name: mqtt-log-volume
              mountPath: /mosquitto/log
            - name: mqtt-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources:
            {{- toYaml .Values.resources.mqttbroker | nindent 12 }}
      volumes:
        - name: mqtt-storage-volume
          hostPath:
            path: /data/mosquitto/data
            type: DirectoryOrCreate
        - name: mqtt-log-volume
          hostPath:
            path: /data/mosquitto/log
            type: DirectoryOrCreate
        - name: mqtt-config
          configMap:
            name: mqttbroker-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mqttbroker-config
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    listener 1883
    allow_anonymous true
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-np
spec:
  type: NodePort
  selector:
    app: mqttbroker
  ports:
  - protocol: TCP
    port: 1883
    nodePort: 30183